# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aa750e498ba23dae61cc9998e2b1ac8eb302f185a33f296d760695a084dcfe474a1f71cd2095ce752b6f73c2fa744a3e60828b634cd7cc4c0bd77ea582a1882

test:
  secret_key_base: 4d003118dd1c9b399f1152c3a1c62af4961e4c9a546e2825d9757fd4190eed6a9e7051b07b61b8839bb1ec387e6ca4ebf76b20ac6fad60db4baff370592d9b58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
